### ISSUE TITLE
code: 404

### ISSUE THREAD

**Issue by zachary** [pixelpeter/laravel5-woocommerce-api-client#53]
local.ERROR: Syntax error {"exception":"[object] (Automattic\\WooCommerce\\HttpClient\\HttpClientException(code: 404): Syntax error at / var/www/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:346)
[stacktrace]
#0 /var/www/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(385): Automattic\\WooCommerce\\HttpClient\\HttpClient->processResponse()
#1 /var/www/vendor/automattic/woocommerce/src/WooCommerce/Client.php(82): Automattic\\WooCommerce\\HttpClient\\HttpClient->request('products/attrib...', 'GET' , Array, Array)
#2 /var/www/vendor/pixelpeter/laravel5-woocommerce-api-client/src/WoocommerceClient.php(58): Automattic\\WooCommerce\\Client->get('products/attrib...', Array)#3 /var/www/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Pixelpeter\\Woocommerce\\WoocommerceClient->get('products/attrib...')
#4 /var/www/app/Console/Commands/ConnWoo.php(42): Illuminate\\Support\\Facades\\Facade::__callStatic('get', Array)
#5 [internal function]: App\\Console\\Commands\\ConnWoo->handle()
#6 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#7 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#9 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Appl ication), Array, Array, NULL)
#10 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#11 /var/www/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#12 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\C onsole\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#13 /var/www/vendor/symfony/console/Application.php(969): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /var/www/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\ConnWoo), Obje ct(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /var/www/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /var/www/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Con sole\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Cons ole\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /var/www/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Co nsole\\Output\\ConsoleOutput))

please advise it.

thanks

**Comment by dmtar** [comment]
@zachary  Did you solve this?

**Comment by pixelpeter** [comment]
Closing as part of archiving this repository.

This package targets Laravel 5.8/6/7 on PHP 7.3/7.4, all of which are end of life, and it is no longer maintained. Its CI can no longer run either — Composer refuses to install those Laravel versions because they are affected by published security advisories.

Apologies for the long silence on this issue. The repository stays available read-only, so the discussion here remains searchable.

If you need a WooCommerce REST client on a current Laravel version, use [automattic/woocommerce](https://github.com/woocommerce/wc-api-php) directly — it is a plain PHP client and needs no Laravel wrapper beyond binding it in a service provider.
